name: surebaladi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  flutter_offline: ^2.1.0
  flutter_svg: ^1.1.0
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  flutter_advanced_drawer: ^1.3.2
  flutter_rating_bar: ^4.0.1
  convex_bottom_bar: ^3.0.0
  dropdown_button2: ^1.6.3
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  easy_localization: ^3.0.1
  flutter_phoenix: ^1.0.0
  flutter_staggered_grid_view: ^0.6.2





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/translations/


  # fonts:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
          weight: 200

    - family: IconBroken
      fonts:
        - asset: assets/icon_broken/icons.ttf


  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
